[build]
command = "npm run build"
publish = "build"

[dev]
command = "npm run start"

[[plugins]]
package = "/plugins/netlify-cache-plugin"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-a11y"

[[plugins]]
package = "netlify-plugin-subfont"
